#!/bin/bash
/bin/systemctl -q restart elasticsearch.service > /dev/null
/bin/systemctl -q restart kibana.service > /dev/null
/bin/systemctl -q restart apm-server.service > /dev/null
/bin/systemctl -q restart nginx.service > /dev/null
